[package]
name = "rustyname"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde = "1.0.216"
serde_derive = "1.0.216"
serde_json = "1.0.134"
